services:
  plex:
    image: 'lscr.io/linuxserver/plex:1.40.4'
    restart: 'always'
    environment:
      TZ: 'Europe/Berlin'
      PUID: 1000
      PGID: 1000
      VERSION: docker
      DOCKER_MODS: ghcr.io/themepark-dev/theme.park:plex
      TP_COMMUNITY_THEME: true
      TP_THEME: catppuccin-macchiato
    env_file:
      - '.env'
    networks:
      - 'proxy_network'
    volumes:
      - 'config:/config'
      - '/mnt/media/:/mnt/media:ro'
    ports:
      - '32400:32400'
      - '32469:32469'
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'proxy_network'
      traefik.http.services.plex-streaming.loadbalancer.server.port: '32400'
      subdomain: 'plex'

volumes:
  config:

networks:
  proxy_network:
    external: true
