# yamllint disable rule:comments-indentation
---
theme: 'dark'

log:
  level: 'debug'

telemetry:
  metrics:
    enabled: false

webauthn:
  ## Disable WebAuthn.
  disable: false

identity_validation:
  reset_password:

authentication_backend:
  password_reset:
    disable: false
  file:
    path: '/config/users.yml'

access_control:
  default_policy: 'deny'
  networks:
    - name: 'internal'
      networks:
        - '192.168.188.0/24'
  rules:
    ###
    # Public apps without auth
    ###
    - domain:
        - 'my.jonnyb.name'
      policy: bypass

    ###
    # Allow all for apps with own auth
    ###
    - domain:
        - 'auth.jonnyb.name'
        - 'homeassistant.jonnyb.name'
        - 'plex.jonnyb.name'
        - 'read.jonnyb.name'
        - 'recipes.jonnyb.name'
      policy: bypass

    ###
    # Allow protected API-Access
    ###
    - domain:
        - 'index.jonnyb.name'
        - 'radarr.jonnyb.name'
        - 'sabnzbd.jonnyb.name'
        - 'sonarr.jonnyb.name'
      resources:
        - '^/api.*'
      policy: bypass

    - subject: group:admin
      domain:
        - 'jonnyb.name'
        - '*.jonnyb.name'
      policy: one_factor


session:
  name: 'authelia_session'
  same_site: 'lax'
  inactivity: '5m'
  expiration: '1h'
  remember_me: '1M'
  cookies:
    - name: 'authelia_session'
      domain: 'jonnyb.name'
      authelia_url: 'https://auth.jonnyb.name'
      default_redirection_url: 'https://my.jonnyb.name'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '1 month'
  redis:
    host: redis

storage:
  local:
    path: '/var/lib/authelia/db.sqlite3'

notifier:
  disable_startup_check: false
  smtp:
    address: 'smtp://smtp.mailbox.org'
    username: 'jboeckel@mailbox.org'
    sender: 'Authelia <jonnyb@mailbox.org>'
    identifier: 'auth.jonnyb.name'
