services:
  docs:
    image: ghcr.io/joniator/documentation:latest
    networks:
      - proxy_network
    labels:
      traefik.enable: true
      traefik.docker.network: proxy_network
      subdomain: docs

networks:
  proxy_network:
    external: true
