alerting:
  discord:
    webhook-url: ${DISCORD_WEBHOOK}

storage:
  type: sqlite
  path: /data/data.db

default_endpoint: &default_endpoint
  interval: 5m
  conditions:
    - "[STATUS] == 200"
  alerts:
    - type: discord
      description: Healthcheck failed
      send-on-resolved: true

default_endpoint_ssl: &default_endpoint_ssl
  interval: 5m
  conditions:
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 92h"
  alerts:
    - type: discord
      description: Healthcheck failed
      send-on-resolved: true

endpoints:
  - name: Boeller-Blog
    group: websites
    url: "https://boeller.dev"
    <<: *default_endpoint_ssl

  - name: Faultier.family
    group: websites
    url: "https://faultier.family"
    <<: *default_endpoint_ssl

  - name: Tazed.club
    group: websites
    url: "https://tazed.club"
    <<: *default_endpoint_ssl

  - name: Tazed Mail
    group: websites
    url: "https://mail.tazed.club"
    <<: *default_endpoint_ssl

  - name: Plex
    group: media
    url: "https://plex.jonnyb.name/web/index.html#!/"
    <<: *default_endpoint_ssl

  - name: Unraid
    group: network
    url: "http://tower"
    <<: *default_endpoint

  - name: HomeAssistant
    group: network
    url: "http://homeassistant:8123"
    <<: *default_endpoint

