http:
  routers:
    unraid:
      rule: 'Host(`unraid.jonnyb.name`)'
      service: 'unraid'
      entrypoints:
        - 'websecure'

    stash:
      rule: 'Host(`stash.jonnyb.name`)'
      service: 'stash'

    homeassistant:
      rule: 'Host(`homeassistant.jonnyb.name`)'
      service: 'homeassistant'

    nodered:
      rule: 'Host(`nodered.jonnyb.name`)'
      service: 'nodered'
      middlewares:
        - nodered_headers

    starlight-local:
      rule: 'Host(`starlight.jonnyb.name`)'
      service: 'starlight-local'


  services:
    unraid:
      loadBalancer:
        servers:
        - url: "http://192.168.188.51"

    stash:
      loadBalancer:
        servers:
          - url: 'http://homeserver:9999'

    homeassistant:
      loadBalancer:
        servers:
          - url: 'http://homeassistant:8123'

    nodered:
      loadBalancer:
        serversTransport: trusted
        servers:
          - url: 'https://homeassistant:1880'

    starlight-local:
      loadBalancer:
        servers:
          - url: 'http://homeserver:4321'
