services:
  homer:
    image: 'b4bz/homer:latest'
    restart: 'always'
    user: 1000:1000
    environment:
      TZ: 'Europe/Berlin'
    networks:
      - 'proxy_network'
    volumes:
      - './homer:/www/assets'
    ports:
      - '8828:8080'
    labels:
      traefik.enable: true
      traefik.docker.network: proxy_network
      subdomain: my

  mealie:
    image: 'hkotel/mealie:latest'
    restart: 'always'
    environment:
      TZ: 'Europe/Berlin'
    env_file:
      - mealie.env
    networks:
      - 'proxy_network'
    volumes:
      - 'mealie:/app/data'
    labels:
      traefik.enable: true
      traefik.docker.network: proxy_network
      traefik.http.services.mealie-services.loadbalancer.server.port: '9000'
      subdomain: 'recipes'

volumes:
  mealie:

networks:
  proxy_network:
    external: true
