services:
  gatus:
    image: 'twinproduction/gatus:latest'
    restart: 'always'
    environment:
      TZ: 'Europe/Berlin'
      DISCORD_WEBHOOK: ${DISCORD_WEBHOOK}
    networks:
      - 'network'
      - 'proxy_network'
    volumes:
      - 'data:/data'
      - './gatus/config:/config'
    labels:
      traefik.enable: true
      traefik.docker.network: proxy_network
      subdomain: up

volumes:
  data:

networks:
  network:
  proxy_network:
    external: true

