services:
  homer:
    image: 'b4bz/homer:latest'
    restart: 'always'
    user: 1000:1000
    environment:
      TZ: 'Europe/Berlin'
    networks:
      - 'proxy_network'
    volumes:
      - './assets:/www/assets'
    labels:
      traefik.enable: true
      subdomain: my

networks:
  proxy_network:
    external: true
