services:
  traefik:
    image: 'traefik:v3.0'
    restart: 'always'
    dns: 192.168.188.1
    environment:
      TZ: 'Europe/Berlin'
    networks:
      - 'network'
      - 'old_proxy'
    ports:
      - '192.168.188.53:80:80'
      - '192.168.188.53:443:443'
    volumes:
      - 'traefik:/etc/traefik'
      - './traefik/config:/etc/traefik/config:ro'
      - './traefik/certs:/etc/traefik/certs:ro'
      - './traefik/traefik.yml:/etc/traefik/traefik.yml:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'

  authelia:
    image: 'authelia/authelia:latest'
    environment:
      TZ: 'Europe/Berlin'
    env_file: 
      - 'authelia.env'
    networks:
      - 'network'
      - 'cache'
    volumes:
      - 'authelia:/var/lib/authelia'
      - './authelia/users.yml:/config/users.yml'  # not read only to allow password changes
      - './authelia/configuration.yml:/config/configuration.yml:ro'
      - './authelia/secrets:/secrets:ro'
    labels:
      traefik.enable: true
      traefik.docker.network: proxy_network
      subdomain: auth

  redis:
    image: 'redis:7-alpine'
    networks:
      - 'cache'

networks:
  network:
  cache:
  old_proxy:
    name: homeserver_proxy
    external: true

volumes:
  traefik:
  authelia:
