services:
  sabnzbd:
    image: 'lscr.io/linuxserver/sabnzbd:latest'
    environment:
      TZ: 'Europe/Berlin'
      DOCKER_MODS: 'ghcr.io/themepark-dev/theme.park:sabnzbd'
      PUID: 1000
      PGID: 1000
      TP_COMMUNITY_THEME: 'true'
      TP_THEME: 'catppuccin-macchiato'
    networks:
      - 'proxy_network'
      - 'usenet'
    volumes:
      - 'sabnzbd_config:/config'
      - 'sabnzbd_incomplete:/incomplete-downloads'
      - 'sabnzbd_downloads:/downloads/sabnzbd'
      - 'sonarr_downloads:/downloads/sonarr'
      - 'radarr_downloads:/downloads/radarr'
      - './sabnzbd/scripts:/scripts'
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'proxy_network'
      subdomain: 'sabnzbd'

  overseerr:
    image: 'lscr.io/linuxserver/overseerr:latest'
    environment:
      DOCKER_MODS: 'ghcr.io/themepark-dev/theme.park:overseerr'
      TZ: 'Europe/Berlin'
      PUID: 1000
      PGID: 1000
      TP_COMMUNITY_THEME: 'true'
      TP_THEME: 'catppuccin-macchiato'
    networks:
      - 'proxy_network'
      - 'usenet'
    volumes:
      - 'overseerr:/config'
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'proxy_network'
      subdomain: 'overseerr'

  nzbhydra:
    image: 'lscr.io/linuxserver/nzbhydra2:latest'
    environment:
      TZ: 'Europe/Berlin'
    networks:
      - 'proxy_network'
      - 'usenet'
    volumes:
      - 'nzbhydra:/config'
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'proxy_network'
      subdomain: 'index'

  radarr:
    image: 'lscr.io/linuxserver/radarr:latest'
    environment:
      TZ: 'Europe/Berlin'
      DOCKER_MODS: 'ghcr.io/themepark-dev/theme.park:radarr'
      PUID: 1000
      PGID: 1000
      TP_COMMUNITY_THEME: 'true'
      TP_THEME: 'catppuccin-macchiato'
    networks:
      - 'proxy_network'
      - 'usenet'
    volumes:
      - 'radarr_config:/config'
      - 'radarr_downloads:/downloads'
      - '/mnt/media/Videos/Filme:/movies'
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'proxy_network'
      subdomain: 'radarr'

  sonarr:
    image: 'lscr.io/linuxserver/sonarr:latest'
    environment:
      TZ: 'Europe/Berlin'
      DOCKER_MODS: 'ghcr.io/themepark-dev/theme.park:sonarr'
      PUID: 1000
      PGID: 1000
      TP_COMMUNITY_THEME: 'true'
      TP_THEME: 'catppuccin-macchiato'
    networks:
      - 'proxy_network'
      - 'usenet'
    volumes:
      - 'sonarr_config:/config'
      - 'sonarr_downloads:/downloads'
      - '/mnt/media/Videos/Serien:/series'
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'proxy_network'
      subdomain: 'sonarr'

volumes:
  sabnzbd_config:
  sabnzbd_incomplete:
  sabnzbd_downloads:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/media/Downloads/sabnzbd'

  overseerr:
  nzbhydra:

  radarr_config:
  radarr_downloads:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/media/Downloads/radarr'

  sonarr_config:
  sonarr_downloads:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/media/Downloads/sonarr'

networks:
  usenet:
  proxy_network:
    external: true
