services:
  nzbhydra:
    image: 'lscr.io/linuxserver/nzbhydra2:latest'
    restart: 'always'
    environment:
      TZ: 'Europe/Berlin'
    networks:
      - 'proxy_network'
      - 'usenet'
    volumes:
      - 'nzbhydra:/config'
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'proxy_network'
      subdomain: 'index'

volumes:
  overseerr:
  nzbhydra:

networks:
  usenet:
  proxy_network:
    external: true
