http:
  middlewares:
    auth:
      forwardAuth:
        address: 'http://authelia:9091/api/verify?rd=https://auth.jonnyb.name/' 
        authResponseHeaders: 
          - 'Remote-User'
          - 'Remote-Name'
          - 'Remote-Email'
          - 'Remote-Groups'
